// Public surface of the deterministic core. No DOM, no Node-only imports.
export { idiv, mulbp, clamp } from './arith.js';
export { createRng, deriveSeed, splitmix32 } from './prng.js';
export { sha256Hex } from './sha256.js';
export { canonical, hashOf } from './canon.js';
export { indexContent, contentHash, STATS, ELEMENTS, REALMS } from './content.js';
export { heroBase, finalStat } from './stats.js';
export { buildHeroUnit, canEquip } from './hero.js';
export { buildMonster } from './monster.js';
export { itemMain, lineValue, rollLines, generateItem, upgradeCost, attemptUpgrade, acceptUpgrade, useMulligan, salvageValue } from './items.js';
export { xpToNext, recruitLevel, recruitCost, trainingCost, encounterRewards } from './progress.js';
export { validateRunbook } from './runbook.js';
export { resolveEncounter, makeContext } from './combat.js';
export { generateDelve, resolveDelve } from './delve.js';
export { resolveFloor, DEATH_SAVE, deathSaveKills } from './floor.js';
export { generateMap, mapFromSeed, moveCost, cellsWithin, TERRAIN_NAMES } from './mapgen.js';
export { createReplay, createFloorReplay, serializeReplay, readReplay, verifyReplay, contentHashOf, ReplayFormatError } from './replay.js';
export { GameError } from './gameerror.js';
export { newGame, recruit, dismiss, equip, setParty, setRunbook, assignThread, unassignThread, buyThread, itemsById, stashCount, topLevel, clone, SAVE_FORMAT, SAVE_VERSION } from './game.js';
export { playDelve, playDelves, batchStop, batchTotals, applyDelveResult, MAX_BATCH } from './game-delve.js';
export { rest, restCost } from './game-rest.js';
export { train } from './game-train.js';
export { addParagonStar, paragonCost } from './game-paragon.js';
export { startExpedition, move, enterFloor, retreat, returnHome, options as expeditionOptions, expeditionMap, siteAt, scaleReward } from './game-expedition.js';
export { upgradeAttempt, acceptAttempt, undoAttempt, salvage, salvageMany } from './game-forge.js';
export { kitOf } from './hero.js';
export { paragonStars, paragonComplete } from './hero.js';
export { validateSave, fillDefaults } from './save.js';
export { lairsFor, lairSpecs, legendStatus, beatenCount, chaosOpen } from './game-legends.js';
export { legendItem } from './items.js';
export { buildLegend } from './monster.js';
export { PHASE } from './phase.js';
